[theme]
# Primary accent color for interactive elements.
primaryColor = "#d33682"

# Background color for the main content area.
backgroundColor = "#15191c"

# Background color used for the sidebar and most interactive widgets.
secondaryBackgroundColor = "#212529"

# Color used for almost all text.
textColor = "#fff"